<?php

/**
 * @file
 * Contains athena_damagetakendiffpermindelt.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function athena_damagetakendiffpermindelt_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the athena_damagetakendiffpermindelt module.
    case 'help.page.athena_damagetakendiffpermindelt':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom entity storage for damage taken diff per min deltas.') . '</p>';
      return $output;

    default:
  }
}
